/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/account.vue')['default']
    Analysis_area: typeof import('./src/components/Analysis_area.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DashBoard: typeof import('./src/components/dashBoard.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scan: typeof import('./src/components/Scan.vue')['default']
  }
}
